project_id = "xdowuirheazerlwatwja"

[functions.generate-sitemap]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.google-search-console-auth]
verify_jwt = true

[functions.fetch-search-console-data]
verify_jwt = true